all:
  hosts:
    localhost:
      ansible_connection: local
      ansible_python_interpreter: "{{ansible_playbook_python}}" #mandatory to set so that you are setting the same Python interpreter for running tasks on the target hosts as the one used for running the playbooks.